# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinyurl',
            name='code',
            field=models.CharField(default='help', max_length=20),
            preserve_default=False,
        ),
    ]
